AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3ReplicaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: amandareplicapolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:GetReplicationConfiguration
          - s3:ListBucket
          - s3:GetObjectVersion
          - s3:GetObjectVersionAcl
          - s3:GetObjectVersionTagging
          - s3:GetObjectVersionForReplication
          Resource: 
          - arn:aws:s3:::amanda-s3-bucket-test
          - arn:aws:s3:::amanda-s3-bucket-test/*
          Effect: Allow
        - Action:
          - s3:ReplicateObject
          - s3:ReplicateDelete
          - s3:ReplicateTags
          - s3:GetObjectVersionTagging
          Resource: 
          - arn:aws:s3:::amanda-s3-bucket-west-test/*
          - arn:aws:s3:::amanda-s3-bucket-west-test
          Effect: Allow
        - Action:
          - kms:Encrypt
          - kms:Decrypt
          Resource: 
            - arn:aws:kms:us-east-1:596174305461:key/d8c44a10-19a2-481c-aa08-62dbd508cd8e
            - arn:aws:kms:us-east-1:596174305461:key/a60a0d53-690c-4f6f-8315-5ff149807f33
            - arn:aws:kms:us-east-1:596174305461:key/97a1b218-1362-42f2-ba85-47328d442772
            - arn:aws:kms:us-west-2:596174305461:key/827ce220-86b9-43c4-952e-188225d5ac72
          Effect: Allow
      Roles:
      - amandaReplicaRole